vim.g.mapleader = ' '
vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('n', '<leader>f', 'gg0vG$=<C-o>')
vim.keymap.set('n', '<leader>l', vim.cmd.Lazy)
vim.keymap.set('n', '<leader>m', vim.cmd.Mason)
vim.keymap.set('n', '<leader>w', vim.cmd.w)
vim.keymap.set('n', '<leader>q', '<cmd>q!<CR>')
vim.keymap.set('n', '<leader>d', '<cmd>e!<CR>')
vim.keymap.set('n', '<leader>r', '<cmd>luafile %<CR>')
vim.keymap.set('n', '<C-h>', '<C-w><C-h>')
vim.keymap.set('n', '<C-j>', '<C-w><C-j>')
vim.keymap.set('n', '<C-k>', '<C-w><C-k>')
vim.keymap.set('n', '<C-l>', '<C-w><C-l>')
vim.keymap.set('n', '<Tab>', vim.cmd.BufferLineCycleNext)
vim.keymap.set('n', '<S-Tab>', vim.cmd.BufferLineCyclePrev)
vim.keymap.set('n', '<leader>e', '<cmd>Neotree toggle<CR>')
vim.keymap.set('n', '<leader>t', '<cmd>TSInstallInfo<CR>')
