vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.clipboard = "unnamedplus"
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.cursorline = true
-- vim.opt.list = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
